### ISSUE TITLE
application crash on multiple simultaneous API traffic requests

### ISSUE THREAD

**Issue by cywang90** [laurinius/MSFSTrafficService#1]
EDIT: On a hunch I did some more testing and was able to identify the cause of the crash to be making a traffic request while the service was still busy with a previous one.

[error.txt](https://github.com/laurinius/MSFSTrafficService/files/6395608/error.txt)

**Comment by laurinius** [comment]
This should now be fixed in the latest release.
In a future release there will also be the option to set a cache interval which will return the last result instead of calling SimConnect again. Keep in mind that as of now each request to the app will cause a call to SimConnect, which can affect the sim performance when done excessively (don't recommend more than 20 times per second).
